import React from "react";

export default function About() {
  return (
    <div>
      <h1>About</h1>
      <ol>
        <li>
          Generated by <a href="https://www.gatsbyjs.org">Gatsby</a>
        </li>
        <li>
          Served by <a href="https://www.netlify.com">Netlify</a>
        </li>
        <li>
          Version Control by{" "}
          <a href="https://github.com/housne/goharry.io">Github</a>
        </li>
      </ol>
    </div>
  );
}
