import React from "react";

export default function About() {
  return (
    <div>
      <h1>About</h1>
      <ol>
        <li>
          Generated by <a href="https://www.gatsbyjs.org">Gatsby</a>
        </li>
      </ol>
    </div>
  );
}
