import React from "react";
import MasterHeader from "../components/MasterHeader";
import Page from "../components/Page";

export default function About() {
  return (
    <Page title="ABOUT">
      <p>Harry's blog</p>
      <ol>
        <li>
          Generated by <a href="https://www.gatsbyjs.org">Gatsby</a>
        </li>
        <li>
          Server and CDN by <a href="https://www.netlify.com">Netlify</a>
        </li>
        <li>
          Version Control by{" "}
          <a href="https://github.com/housne/goharry.io">Github</a>
        </li>
        <li>
          Search by <a href="https://www.algolia.com">Algolia</a>
        </li>
        <li>
          Comment service by <a href="https://staticman.net">Staticman</a>
        </li>
      </ol>
    </Page>
  );
}
